from pathlib import Path

DB_PATH = Path(__file__).parent.parent.parent / "lunar_run.db"
DAYS_TOTAL = 15
BASE_COORDINATES = {"x": 400, "y": 250}
REPAIR_COST = 60

MAX_RATING = 100
MIN_RATING = 0
RATING_LOSS_EXPIRED = 5
RATING_LOSS_CRASH_BASE = 8
RATING_GAIN_DELIVERY = 2

BATTERY_RECHARGE_FACTOR = 0.3
AUTO_REPAIR_BATTERY_FACTOR = 0.4
PAID_REPAIR_BATTERY_FACTOR = 0.6

MAX_ORDERS_PER_DAY = 3
MIN_ORDERS_PER_DAY = 2
IMPOSSIBLE_ORDER_PROBABILITY = 0.12
WEIGHT_MIN = 3
WEIGHT_MAX = 30
IMPOSSIBLE_WEIGHT_MIN = 37
IMPOSSIBLE_WEIGHT_MAX = 48
URGENCY_DAYS_MIN = 2
URGENCY_DAYS_MAX = 5